const quizData=[
 {q:"What is 9 × 7?",c:["56","63","72","81"],a:1},
 {q:"Which organelle is known as the powerhouse of the cell?",c:["Nucleus","Ribosome","Mitochondrion","Cell wall"],a:2},
 {q:"What is the area of a rectangle 8 units by 5 units?",c:["13","26","40","80"],a:2},
 {q:"Which word is closest in meaning to 'rapid'?",c:["slow","fast","quiet","heavy"],a:1}
];
let quizIndex=0;
function renderQuiz(){const x=quizData[quizIndex];document.getElementById('quizBox').innerHTML=`<div class="question">${x.q}</div><div class="choices">${x.c.map((v,i)=>`<label><input type="radio" name="quiz" value="${i}"> ${String.fromCharCode(65+i)}. ${v}</label>`).join('')}</div>`;document.getElementById('quizFeedback').textContent='';}
document.getElementById('newQuiz').onclick=()=>{quizIndex=(quizIndex+1)%quizData.length;renderQuiz();};
document.getElementById('checkQuiz').onclick=()=>{const pick=document.querySelector('input[name="quiz"]:checked');const f=document.getElementById('quizFeedback');if(!pick){f.textContent='Choose an answer first.';return;}f.textContent=Number(pick.value)===quizData[quizIndex].a?'✅ Correct! Great job.':'❌ Not quite. Try again!';};renderQuiz();

const cards=[['Photosynthesis','How plants convert light energy into chemical energy.'],['Hypothesis','A testable explanation or prediction.'],['Denominator','The bottom number in a fraction.'],['Metaphor','A comparison that says one thing is another.']];let cardIndex=0;
function showCard(){document.getElementById('flashFront').textContent=cards[cardIndex][0];document.getElementById('flashBack').textContent=cards[cardIndex][1];document.getElementById('flashcard').classList.remove('flipped');}
const flip=()=>document.getElementById('flashcard').classList.toggle('flipped');document.getElementById('flashcard').onclick=flip;document.getElementById('flipCard').onclick=flip;document.getElementById('nextCard').onclick=()=>{cardIndex=(cardIndex+1)%cards.length;showCard()};document.getElementById('prevCard').onclick=()=>{cardIndex=(cardIndex-1+cards.length)%cards.length;showCard()};

let tasks=JSON.parse(localStorage.getItem('schoolHelperTasks')||'[]');function drawTasks(){const ul=document.getElementById('homeworkList');ul.innerHTML=tasks.map((t,i)=>`<li class="${t.done?'done':''}"><span>${t.text}</span><div><button class="secondary" onclick="toggleTask(${i})">✓</button> <button class="secondary" onclick="deleteTask(${i})">×</button></div></li>`).join('');localStorage.setItem('schoolHelperTasks',JSON.stringify(tasks));}
window.toggleTask=i=>{tasks[i].done=!tasks[i].done;drawTasks()};window.deleteTask=i=>{tasks.splice(i,1);drawTasks()};document.getElementById('homeworkForm').onsubmit=e=>{e.preventDefault();const inp=document.getElementById('homeworkInput');tasks.push({text:inp.value.trim(),done:false});inp.value='';drawTasks();};drawTasks();

let total=25*60,remaining=total,timerId=null;function displayTimer(){const m=Math.floor(remaining/60),s=remaining%60;document.getElementById('timerDisplay').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;}function stop(){clearInterval(timerId);timerId=null}document.getElementById('startTimer').onclick=()=>{if(timerId)return;timerId=setInterval(()=>{if(remaining>0){remaining--;displayTimer()}else{stop();alert('Study session complete! Great work.')}},1000)};document.getElementById('pauseTimer').onclick=stop;document.getElementById('resetTimer').onclick=()=>{stop();total=Math.max(1,Number(document.getElementById('timerMinutes').value)||25)*60;remaining=total;displayTimer()};document.getElementById('timerMinutes').onchange=()=>document.getElementById('resetTimer').click();displayTimer();

const chat=document.getElementById('chatMessages');function botReply(q){const s=q.toLowerCase();if(s.includes('study'))return 'Try a 25-minute focused study block, then take a 5-minute break. Use the flashcards to review after each block.';if(s.includes('homework'))return 'Break the assignment into small steps, start with the shortest task, and add each item to the Homework Tracker.';if(s.includes('math'))return 'Write down what is known, what you need to find, and the formula or rule that connects them. Then solve one step at a time.';if(s.includes('science'))return 'Use cause-and-effect thinking: identify the system, what changes, and what evidence supports the result.';if(s.includes('word')||s.includes('vocab'))return 'Put the word on the front of a flashcard. On the back, write the definition and one sentence using the word.';return 'I can help with study planning, homework organization, math steps, science concepts, and vocabulary practice. Try asking a more specific school question!';}
document.getElementById('chatForm').onsubmit=e=>{e.preventDefault();const input=document.getElementById('chatInput');const q=input.value.trim();if(!q)return;chat.insertAdjacentHTML('beforeend',`<div class="bubble user">${q.replace(/[<>]/g,'')}</div>`);input.value='';setTimeout(()=>{chat.insertAdjacentHTML('beforeend',`<div class="bubble bot">${botReply(q)}</div>`);chat.scrollTop=chat.scrollHeight;},250);chat.scrollTop=chat.scrollHeight;};

const pages=[['Math','Area of a circle: A = πr²','Pythagorean theorem: a² + b² = c²','Science','Water: H₂O','Speed = distance ÷ time'],['English','Noun: person, place, thing, or idea','Verb: action or state of being','History','A primary source comes from the time being studied.','A timeline puts events in chronological order.'],['Study Skills','Review a little each day.','Practice recalling without looking at notes.','Organization','Use a to-do list.','Start big projects before the due date.']];let pageIndex=0;document.getElementById('nextBook').onclick=()=>{pageIndex=(pageIndex+1)%pages.length;const p=pages[pageIndex];document.querySelector('.left-page').innerHTML=`<h3>${p[0]}</h3><p>${p[1]}</p><p>${p[2]}</p>`;document.querySelector('.right-page').innerHTML=`<h3>${p[3]}</h3><p>${p[4]}</p><p>${p[5]}</p>`;};
